// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqAWyzGcCrvUkhsVO0KMrnUxIcxWRlYgQ',
    appId: '1:1039119672171:web:08a32640c431c14623222e',
    messagingSenderId: '1039119672171',
    projectId: 'daftartugas-e46e9',
    authDomain: 'daftartugas-e46e9.firebaseapp.com',
    storageBucket: 'daftartugas-e46e9.firebasestorage.app',
    measurementId: 'G-SNZYHX003R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA22aaEQsxCixemEmTLtGaBFOYkTRNA8qU',
    appId: '1:1039119672171:android:154b76f4a9158b8b23222e',
    messagingSenderId: '1039119672171',
    projectId: 'daftartugas-e46e9',
    storageBucket: 'daftartugas-e46e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtU91j5LN5qZ6cDbELJVNnF9rP-oG6Sz8',
    appId: '1:1039119672171:ios:35f6a4a47aa2fe8923222e',
    messagingSenderId: '1039119672171',
    projectId: 'daftartugas-e46e9',
    storageBucket: 'daftartugas-e46e9.firebasestorage.app',
    iosBundleId: 'com.example.serawaiLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtU91j5LN5qZ6cDbELJVNnF9rP-oG6Sz8',
    appId: '1:1039119672171:ios:35f6a4a47aa2fe8923222e',
    messagingSenderId: '1039119672171',
    projectId: 'daftartugas-e46e9',
    storageBucket: 'daftartugas-e46e9.firebasestorage.app',
    iosBundleId: 'com.example.serawaiLearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD29gtADMag1RGglUcoMwl8Uxqx11FA20I',
    appId: '1:1039119672171:web:cbe4caa25a73b3bc23222e',
    messagingSenderId: '1039119672171',
    projectId: 'daftartugas-e46e9',
    authDomain: 'daftartugas-e46e9.firebaseapp.com',
    storageBucket: 'daftartugas-e46e9.firebasestorage.app',
    measurementId: 'G-9YGZ0JP8H4',
  );
}
